### ISSUE TITLE
Korrekte Attribution gegenüber der IHK

### ISSUE THREAD

**Issue by ChargingBulle** [StefanMacke/latex-vorlage-fiae#11]
Hallo Stefan, diese Vorlage sieht sehr gut aus und ich erwäge diese für meine IHK Dokumentation zu verwenden.

Wie habe ich mir die Autor-Attribution im Sinne von von CC BY-SA 4.0 vorzustellen? Möchtest du namentlich in der ausgedruckten Version erwähnt, werden welche der IHK vorgelegt wird oder beschränkt sich BY lediglich auf Weitergabe der Vorlage im .tex Format?
Das Nennen von Dritten im "Ergebnis" PDF wäre mir persönlich unlieb und dh. frage ich lieber noch mal.

**Comment by danielkoerner** [comment]
Siehe [Fußnote 4, Vorlage.tex](https://github.com/StefanMacke/latex-vorlage-fiae/blob/faf631a04822af9d555797a34f487dbcda0fcc59/Vorlage.tex#L34) :-)

**Comment by StefanMacke** [comment]
So ist es! :-) Einfach in den Quelltext schreiben. Im PDF muss nichts sichtbar sein. Natürlich habe ich aber nichts dagegen, wenn das trotzdem der Fall ist! ;-)
