### ISSUE TITLE
Funktioniert diese Vorlage auch fuer IHK Duesseldorf?

### ISSUE THREAD

**Issue by xetra11** [StefanMacke/latex-vorlage-fiae#9]
Ein Kollege hat mir gesagt, dass diese Vorlage nicht fuer die IHK Duesseldorf funktioniert. Stimmt das? Oder kann ich sorglos damit arbeiten?

Gruss und Danke fuer die Muehe!

**Comment by ypid** [comment]
Ohne jetzt Stefan zuvorgreifen zu wollen kann ich nur aus seinem Podcast und meiner Erfahrung mit der IHK Weingarten berichten. Die [IHKs] haben doch alle eigene Richlinien was eigentlich Sinnlos ist. "sorglos" funktioniert also leider nicht und ist auch unpassend formuliert, es geht hier immerhin um den Abschluss deiner Ausbildung (wie Stefan zu sagen pflegt). Ich denke du bist in der Pflicht zu prüfen, ob diese Vorlage alle Formalien erfüllt. Ich halte es für Sinnvoll, eine Liste von sollchen Kompatibilitäten mit Link zur spec und Version der spec der jeweiligen IHKs in diesem Repo von Nutzern/Auszubildenten (oder den IHKs selbst, man kann ja träumen) per PR einreicheichen zu lassen und hier zu pflegen.

**Comment by StefanMacke** [comment]
@ypid Dem ist nichts mehr hinzuzufügen! :-)
